### PR TITLE
Fixed random newlines in our dataset

### PR DESCRIPTION
**Pull request by shomali2**
Fixed the random newlines within some of lines in our dataset & saved the fixed dataset to "fixed_final_dataset.csv"

### CODE REVIEW

**Review by sumeetk321 — DISMISSED** [review]
Looks good, just resolve the merge conflict with the updated main branch

**Comment by shomali2** [comment]
Readded manage.ipynb & moved the jupyter note books to a separate folder to keep repo organized, should be good to merge now

**Review by sumeetk321 — COMMENTED** [review]
Looks good, ready to merge

**Review by sumeetk321 — APPROVED** [review]
Looks good, ready to merge

**Pull request merged**
